name: Main
on: [push, pull_request]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew :build :test
